/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface KalkulatorBKDPendidikanInterface extends Interface {
    getFunction(nameOrSignature: "hitungBimbinganKKNPKLMagang" | "hitungBimbinganSeminarMahasiswa" | "hitungDetaseringPencangkokan" | "hitungJabatanPimpinanPerguruanTinggi" | "hitungMembimbingDosenLebihRendah" | "hitungOrasiIlmiah" | "hitungPelatihanDasar" | "hitungPembimbinganTugasAkhir" | "hitungPembinaKegiatanMahasiswa" | "hitungPendampinganMahasiswaLuarInstitusi" | "hitungPendidikanDokterEvaluasiPeserta" | "hitungPendidikanDokterKeputusanKlinisAkhir" | "hitungPendidikanDokterKomunikasiSpesialis" | "hitungPendidikanDokterPelaksanaanPembelajaran" | "hitungPendidikanFormalDoktor" | "hitungPengajaran" | "hitungPengembanganBahanAjar" | "hitungPengembanganProgramKuliah" | "hitungPengujiUjianAkhir" | "jumlahkanSKS"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'hitungBimbinganKKNPKLMagang', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungBimbinganSeminarMahasiswa', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungDetaseringPencangkokan', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungJabatanPimpinanPerguruanTinggi', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungMembimbingDosenLebihRendah', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungOrasiIlmiah', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungPelatihanDasar', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungPembimbinganTugasAkhir', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungPembinaKegiatanMahasiswa', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungPendampinganMahasiswaLuarInstitusi', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungPendidikanDokterEvaluasiPeserta', values?: undefined): string;
encodeFunctionData(functionFragment: 'hitungPendidikanDokterKeputusanKlinisAkhir', values?: undefined): string;
encodeFunctionData(functionFragment: 'hitungPendidikanDokterKomunikasiSpesialis', values?: undefined): string;
encodeFunctionData(functionFragment: 'hitungPendidikanDokterPelaksanaanPembelajaran', values?: undefined): string;
encodeFunctionData(functionFragment: 'hitungPendidikanFormalDoktor', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungPengajaran', values: [BigNumberish, BigNumberish, BigNumberish, boolean, boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungPengembanganBahanAjar', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungPengembanganProgramKuliah', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hitungPengujiUjianAkhir', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'jumlahkanSKS', values: [BigNumberish[]]): string;

    decodeFunctionResult(functionFragment: 'hitungBimbinganKKNPKLMagang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungBimbinganSeminarMahasiswa', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungDetaseringPencangkokan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungJabatanPimpinanPerguruanTinggi', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungMembimbingDosenLebihRendah', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungOrasiIlmiah', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPelatihanDasar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPembimbinganTugasAkhir', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPembinaKegiatanMahasiswa', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPendampinganMahasiswaLuarInstitusi', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPendidikanDokterEvaluasiPeserta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPendidikanDokterKeputusanKlinisAkhir', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPendidikanDokterKomunikasiSpesialis', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPendidikanDokterPelaksanaanPembelajaran', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPendidikanFormalDoktor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPengajaran', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPengembanganBahanAjar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPengembanganProgramKuliah', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hitungPengujiUjianAkhir', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jumlahkanSKS', data: BytesLike): Result;
  }

  

  export interface KalkulatorBKDPendidikan extends BaseContract {
    
    connect(runner?: ContractRunner | null): KalkulatorBKDPendidikan;
    waitForDeployment(): Promise<this>;

    interface: KalkulatorBKDPendidikanInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    hitungBimbinganKKNPKLMagang: TypedContractMethod<
      [jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungBimbinganSeminarMahasiswa: TypedContractMethod<
      [jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungDetaseringPencangkokan: TypedContractMethod<
      [lokasi: BigNumberish, jumlahKegiatan: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungJabatanPimpinanPerguruanTinggi: TypedContractMethod<
      [jabatan: BigNumberish, jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungMembimbingDosenLebihRendah: TypedContractMethod<
      [jenis: BigNumberish, jumlahOrang: BigNumberish, jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungOrasiIlmiah: TypedContractMethod<
      [jumlahOrasi: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungPelatihanDasar: TypedContractMethod<
      [jumlahSertifikat: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungPembimbinganTugasAkhir: TypedContractMethod<
      [peran: BigNumberish, jenisTugasAkhir: BigNumberish, jumlahMahasiswa: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungPembinaKegiatanMahasiswa: TypedContractMethod<
      [jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungPendampinganMahasiswaLuarInstitusi: TypedContractMethod<
      [jenjang: BigNumberish, jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungPendidikanDokterEvaluasiPeserta: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hitungPendidikanDokterKeputusanKlinisAkhir: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hitungPendidikanDokterKomunikasiSpesialis: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hitungPendidikanDokterPelaksanaanPembelajaran: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hitungPendidikanFormalDoktor: TypedContractMethod<
      [jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungPengajaran: TypedContractMethod<
      [sksMataKuliah: BigNumberish, jumlahPertemuanRencana: BigNumberish, jumlahPertemuanRealisasi: BigNumberish, semesterPenuh: boolean, teamTeaching: boolean, persenPorsiDosen: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungPengembanganBahanAjar: TypedContractMethod<
      [jenisBahanAjar: BigNumberish, jumlahNaskah: BigNumberish, peranTim: BigNumberish, jumlahAnggotaTim: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungPengembanganProgramKuliah: TypedContractMethod<
      [jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hitungPengujiUjianAkhir: TypedContractMethod<
      [peranPenguji: BigNumberish, jumlahMahasiswa: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    jumlahkanSKS: TypedContractMethod<
      [daftarNilaiSKSX100: BigNumberish[], ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'hitungBimbinganKKNPKLMagang'): TypedContractMethod<
      [jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungBimbinganSeminarMahasiswa'): TypedContractMethod<
      [jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungDetaseringPencangkokan'): TypedContractMethod<
      [lokasi: BigNumberish, jumlahKegiatan: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungJabatanPimpinanPerguruanTinggi'): TypedContractMethod<
      [jabatan: BigNumberish, jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungMembimbingDosenLebihRendah'): TypedContractMethod<
      [jenis: BigNumberish, jumlahOrang: BigNumberish, jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungOrasiIlmiah'): TypedContractMethod<
      [jumlahOrasi: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPelatihanDasar'): TypedContractMethod<
      [jumlahSertifikat: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPembimbinganTugasAkhir'): TypedContractMethod<
      [peran: BigNumberish, jenisTugasAkhir: BigNumberish, jumlahMahasiswa: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPembinaKegiatanMahasiswa'): TypedContractMethod<
      [jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPendampinganMahasiswaLuarInstitusi'): TypedContractMethod<
      [jenjang: BigNumberish, jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPendidikanDokterEvaluasiPeserta'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPendidikanDokterKeputusanKlinisAkhir'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPendidikanDokterKomunikasiSpesialis'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPendidikanDokterPelaksanaanPembelajaran'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPendidikanFormalDoktor'): TypedContractMethod<
      [jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPengajaran'): TypedContractMethod<
      [sksMataKuliah: BigNumberish, jumlahPertemuanRencana: BigNumberish, jumlahPertemuanRealisasi: BigNumberish, semesterPenuh: boolean, teamTeaching: boolean, persenPorsiDosen: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPengembanganBahanAjar'): TypedContractMethod<
      [jenisBahanAjar: BigNumberish, jumlahNaskah: BigNumberish, peranTim: BigNumberish, jumlahAnggotaTim: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPengembanganProgramKuliah'): TypedContractMethod<
      [jumlahSemester: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hitungPengujiUjianAkhir'): TypedContractMethod<
      [peranPenguji: BigNumberish, jumlahMahasiswa: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'jumlahkanSKS'): TypedContractMethod<
      [daftarNilaiSKSX100: BigNumberish[], ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }